@startuml Simpson

class Ventana
class MenuInicio
class Metodo
class Ecuacion
class Intervalo

Ventana --o MenuInicio
MenuInicio *-- Metodo
Metodo o-- Ecuacion
Ecuacion --> Metodo 
Ecuacion *-- Intervalo

@enduml