@startuml Simpson
class MenuInicio
class Simpson
class Intervalo
class Function
class tinyexpr

MenuInicio o-- Simpson 
Simpson o-- tinyexpr
Simpson *-- Function 
Function o-- tinyexpr
Function *-- Intervalo

@enduml