@startuml Simpson
class Ventana
class MenuInicio
class Metodo
class Ecuacion
class Intervalo

Ventana --o MenuInicio
MenuInicio *-- Metodo
Metodo o-- Ecuacion
Simpson --> Metodo
Ecuacion --> Metodo 
Metodo o-- Function
Ecuacion *-- Intervalo
@enduml